version: "3.7"

services:
  example-test-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./exampleTestServer1.js:/usr/app/exampleTestServer1.js:cached
      - ./node_modules:/usr/app/node_modules:cached
      - ./package.json:/usr/app/package.json:cached
    working_dir: /usr/app
    command: npm run start-example-test-server-1
    ports:
      - 4001:4000

  example-test-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./exampleTestServer2.js:/usr/app/exampleTestServer2.js:cached
      - ./node_modules:/usr/app/node_modules:cached
      - ./package.json:/usr/app/package.json:cached
    working_dir: /usr/app
    command: npm run start-example-test-server-2
    ports:
      - 4002:4000

  apollo-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./apollo-gateway.js:/usr/app/apollo-gateway.js:cached
      - ./gateway-server.js:/usr/app/gateway-server.js:cached
      - ./node_modules:/usr/app/node_modules:cached
      - ./package.json:/usr/app/package.json:cached
    working_dir: /usr/app
    command: npm run start-apollo-gateway
    ports:
      - 4000:4000
      - 51457:4000
    links:
      - example-test-server-1
      - example-test-server-2
    environment:
      - SERVER_1_URL=http://example-test-server-1:4000/graphql
      - SERVER_2_URL=http://example-test-server-2:4000/graphql